import { pixelsPerSecond } from "../constants";

export const genTextElement = (
  text: string,
  start: number,
  end: number,
  width: number,
  height: number,
  x: number,
  y: number
) => {
  const duration = (end - start) * 1000; // in miliseconds
  const startAt = start * pixelsPerSecond;

  return {
    type: "text",
    name: text,
    opacity: 1,
    visible: true,
    selectable: true,
    removable: true,
    alwaysOnTop: false,
    showInExport: true,
    x,
    y,
    width,
    height,
    rotation: 0,
    animations: [],
    blurEnabled: false,
    blurRadius: 10,
    brightnessEnabled: false,
    brightness: 0,
    sepiaEnabled: false,
    grayscaleEnabled: false,
    shadowEnabled: false,
    shadowBlur: 5,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowColor: "black",
    shadowOpacity: 1,
    draggable: true,
    resizable: true,
    contentEditable: true,
    styleEditable: true,
    text: text,
    placeholder: "",
    fontSize: 30,
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    textDecoration: "",
    fill: "black",
    align: "center",
    verticalAlign: "top",
    strokeWidth: 0,
    stroke: "black",
    lineHeight: 1.2,
    letterSpacing: 0,
    backgroundEnabled: false,
    backgroundColor: "#7ED321",
    backgroundOpacity: 1,
    backgroundCornerRadius: 0.5,
    backgroundPadding: 0.5,
    custom: {
      startAt: startAt,
      duration: duration,
      endAt: duration,
      type: "transcript",
      start,
      end,
    },
  };
};
